services:
  - type: web
    name: recipe-rover
    env: python
    plan: free
    buildCommand: cd recipe-rover && pip install -r requirements.txt
    startCommand: cd recipe-rover/src && gunicorn app:app
    envVars:
      - key: PORT
        value: 8000
